/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct usuario {
	char nickname[10];
};
typedef struct usuario usuario;

struct msg {
	int id_usuario;
	char conteudo_mensagem[100];
};
typedef struct msg msg;

#define PROG 0x30009999
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define conectar_usuario 1
extern  int * conectar_usuario_1(usuario *, CLIENT *);
extern  int * conectar_usuario_1_svc(usuario *, struct svc_req *);
#define resgatar_usuario 2
extern  usuario * resgatar_usuario_1(int *, CLIENT *);
extern  usuario * resgatar_usuario_1_svc(int *, struct svc_req *);
#define enviar_mensagem 3
extern  int * enviar_mensagem_1(msg *, CLIENT *);
extern  int * enviar_mensagem_1_svc(msg *, struct svc_req *);
#define retornar_numero_mensagens 4
extern  int * retornar_numero_mensagens_1(void *, CLIENT *);
extern  int * retornar_numero_mensagens_1_svc(void *, struct svc_req *);
#define resgatar_mensagem 5
extern  msg * resgatar_mensagem_1(int *, CLIENT *);
extern  msg * resgatar_mensagem_1_svc(int *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define conectar_usuario 1
extern  int * conectar_usuario_1();
extern  int * conectar_usuario_1_svc();
#define resgatar_usuario 2
extern  usuario * resgatar_usuario_1();
extern  usuario * resgatar_usuario_1_svc();
#define enviar_mensagem 3
extern  int * enviar_mensagem_1();
extern  int * enviar_mensagem_1_svc();
#define retornar_numero_mensagens 4
extern  int * retornar_numero_mensagens_1();
extern  int * retornar_numero_mensagens_1_svc();
#define resgatar_mensagem 5
extern  msg * resgatar_mensagem_1();
extern  msg * resgatar_mensagem_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usuario (XDR *, usuario*);
extern  bool_t xdr_msg (XDR *, msg*);

#else /* K&R C */
extern bool_t xdr_usuario ();
extern bool_t xdr_msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
